spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:ec2-44-194-4-127.compute-1.amazonaws.com}:${DB_PORT:5432}/${DB_DATABASE:defmupdr81c3bo}
    username: ${DB_USER:rergkejkisekdy}
    password: ${DB_PASSWORD:41482075febe37dee189966323cd0aa1d2a0279954effa2903867ea745f516ff}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SHOW_SQL:false}
  liquibase:
    change-log: classpath:/liquibase/changelog.yaml
server:
  port: ${APP_PORT:8080}